/*
  name:poem.c 
  author:gled fish
  time:2021/10/31
*/
#include<stdio.h>
int main() {
	printf(
	" To be, or not to be, that is the question:\n"
    " Whether ¡¯tis nobler in the mind to suffer\n"
    " The slings and arrows of outrageous fortune,\n"
    " Or to take Arms against a Sea of troubles,\n"
    " And by opposing end them: to die, to sleep\n"
    " No more; and by a sleep, to say we end\n"
    " The heart-ache, and the thousand natural shocks\n"
    " That Flesh is heir to? ¡¯Tis a consummation\n"
    " Devoutly to be wished. To die, to sleep,\n" 
    " perchance to Dream; aye, there¡¯s the rub,\n"
    " For in that sleep of death, what dreams may come,\n"
    " When we have shuffled off this mortal coil,\n"
    " Must give us pause. There¡¯s the respect\n"
    " That makes Calamity of so long life:\n"
    " For who would bear the Whips and Scorns of time,\n"
    " The Oppressor¡¯s wrong, theproudman¡¯s Contumely,\n"
    " The pangs ofdispisedLove, the Law¡¯s delay,\n"
    " The insolence of Office, and the spurns\n"
    " That patient merit of the unworthy takes,\n"
    " When he himself might his Quietus make\n"
    " With a bare Bodkin? Who would Fardels bear,\n"
    " To grunt and sweat under a weary life,\n"
    " But that the dread of something after death,\n"
    " The undiscovered country, from whose bourn\n"
    " No traveller returns, puzzles the will,\n"
    " And makes us rather bear those ills we have,\n"
    " Than fly to others that we know not of.\n"
    " Thus conscience does make cowards of us all,\n"
    " And thus the native hue of Resolution\n"
    " Is sicklied o¡¯er, with the pale cast of Thought,\n"
    " With this regard their Currents turnawry,\n"
    " And lose the name of Action. Soft you now,\n"
    " Be all my sins remember¡¯d.\n"
    " Hamlet, Prince of Denmark: Act ff, Scene ff\n"
    " To be, or not to be, that is the question:\n"
    " Whether ¡¯tis nobler in the mind to suffer\n"
    " The slings and arrows of outrageous fortune,\n"
    " Or to take arms against a sea of troubles\n"
    " And by opposing end them. To die ¡ªto sleep,\n"
    " No more; and by a sleep to say we end\n"
    " The heart-ache, and the thousand natural shocks\n"
    " That flesh is heir to, ¡¯Tis a consummation\n"
    " Devoutly to be wish¡¯d. To die, to sleep;\n"
    " To sleep, perchance to dream ¡ªay, there¡¯s the rub:\n"
    " For in that sleep of death what dreams may come,\n"
    " When we have shuffled off this mortal coil,\n"
    " Must give us pause. There¡¯s the respect\n"
    " That makes calamity of so long life.\n"
    " For who would bear the whips and scorns of time,\n"
    " Th¡¯ oppressor¡¯s wrong, the proud man¡¯s contumely,\n"
    " The pangs of despised love, the law¡¯s delay,\n"
    " The insolence of office, and the spurns\n"
    " That patient merit of th¡¯ unworthy takes,\n"
    " When he himself might his quietus make\n"
    " With a bare bodkin? Who would fardels bear,\n"
    " To grunt and sweat under a weary life,\n"
    " But that the dread of something after death,\n"
    " The undiscover¡¯d country from whose bourn\n"
    " No traveller returns, puzzles the will,\n"
    " And makes us rather bear those ills we have\n"
    " Thus conscience does make cowards of us all,\n"
    " And thus the native hue of resolution\n"
    " Is sicklied o¡¯er with the pale cast of thought,\n"
    " And enterprises of great pitch and moment\n"
    " With this regard their currents turn awry\n"
    " And lose the name of action.\n"
    );
    return 0;
}
